version: "3.8"

services:
    sqlite3:
        image: nouchka/sqlite3:latest
        stdin_open: true
        tty: true
        volumes:
            - ./code/sqlite3:///./models.db
        restart: unless-stopped

    web:
        build: .
        command: bash -c "alembic upgrade head && python -m uvicorn src.server:app --host 0.0.0.0 --port 8000 --reload"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - sqlite3

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5050:80"
        depends_on:
            - sqlite3
