"""First migration

Revision ID: 4c5ddfd985df
Revises: 51ece938046c
Create Date: 2022-09-19 04:03:24.040055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5ddfd985df'
down_revision = '51ece938046c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
