"""First migration

Revision ID: 9f0052218663
Revises: 4c5ddfd985df
Create Date: 2022-09-19 04:06:33.085697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0052218663'
down_revision = '4c5ddfd985df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
