"""Primeira migração.

Revision ID: efc19c2dd95d
Revises: 0eed13ef6e7c
Create Date: 2022-09-18 00:35:05.285768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc19c2dd95d'
down_revision = '0eed13ef6e7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
